#spring.application.name=lab12026p
#server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/lab12026p
#spring.datasource.username=arquisoftlabuser
#spring.datasource.password=1596
#spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.default_schema=lab12026p_schema

#logging.level.org.springframework=INFO
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#spring.transaction.default-timeout=30
#spring.transaction.rollback-on-commit-failure=true

#spring.mvc.contentnegotiation.favor-path-extension=false
#spring.mvc.contentnegotiation.favor-parameter=false
#spring.mvc.contentnegotiation.media-types.json=application/json


spring.application.name=lab12026p

# Puerto dinámico para Render
server.port=${PORT:8080}

# =========================
# DATABASE (RENDER POSTGRESQL)
# =========================
spring.datasource.url=jdbc:postgresql://dpg-d7e40flckfvc73f5ggvg-a:5432/lab2db_untj
spring.datasource.username=lab2db_untj_user
spring.datasource.password=mQRTreAciXXHKmFgzm8Hl6Qz9kvDmPDk
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

# =========================
# LOGGING
# =========================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# =========================
# TRANSACTIONS
# =========================
spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true

# =========================
# MVC CONFIG
# =========================
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json